# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
# Import standard library dependencies
import os
import shutil

# Import internal project modules
from utils.logger import log_info, log_warning, log_error


def move_files(operations, dry_run):
    """
    Executes filesystem operations generated by execution_planner.py

    EXECUTION CONTRACT:
    - Each operation is fully independent
    - Failure in one operation MUST NOT affect others
    - No decision making or planning occurs here
    """

    # -------------------------------------------------
    # VALIDATE INPUT
    # -------------------------------------------------
    if not isinstance(operations, list):

        log_error(
            f"move_error | "
            f"reason=invalid_operations_type "
            f"received_type={type(operations).__name__}"
        )
        return

    log_info(f"move_start | operations={len(operations)} dry_run={dry_run}")

    # -------------------------------------------------
    # EXECUTION STATE
    # -------------------------------------------------
    total_moved = 0
    category_summary = {}
    created_folders = set()

    # -------------------------------------------------
    # EXECUTION LOOP (ISOLATED PER OPERATION)
    # -------------------------------------------------
    for op in operations:

        # =================================================
        # OPERATION ISOLATION BOUNDARY
        # =================================================
        # Each operation is fully independent and failure-safe
        try:

            # -------------------------------------------------
            # OPERATION STRUCTURE VALIDATION
            # -------------------------------------------------
            if not isinstance(op, dict):

                log_warning(
                    f"move_skip | "
                    f"reason=invalid_operation_structure "
                    f"received_type={type(op).__name__}"
                )
                continue

            source_path = op.get("source_path")
            destination_path = op.get("destination_path")
            category = op.get("category")
            file = op.get("file")
            folder_name = op.get("folder_name")

            # -------------------------------------------------
            # REQUIRED FIELD VALIDATION
            # -------------------------------------------------
            if not all([source_path, destination_path, category, file]):

                log_warning(
                    f"move_skip | "
                    f"reason=missing_fields "
                    f"file={file} "
                    f"source_path={source_path} "
                    f"destination_path={destination_path}"
                )
                continue

            # -------------------------------------------------
            # FOLDER CREATION (SAFE + ONCE PER FOLDER)
            # -------------------------------------------------
            if folder_name and folder_name not in created_folders:

                created_folders.add(folder_name)

                if dry_run:

                    log_info(
                        f"folder_create_simulation | "
                        f"folder={folder_name}"
                    )

                else:

                    try:
                        os.makedirs(
                            os.path.dirname(destination_path),
                            exist_ok=True
                        )

                        log_info(
                            f"folder_created | "
                            f"folder={folder_name}"
                        )

                    except Exception as e:

                        log_error(
                            f"folder_create_failed | "
                            f"reason=os_error "
                            f"destination_path={destination_path}",
                            error=e
                        )
                        continue

            # -------------------------------------------------
            # SOURCE VALIDATION
            # -------------------------------------------------
            if not os.path.exists(source_path):

                log_warning(
                    f"move_skip | "
                    f"reason=file_missing "
                    f"file={file} "
                    f"source_path={source_path}"
                )
                continue

            # -------------------------------------------------
            # EXECUTION PHASE
            # -------------------------------------------------
            if dry_run:

                log_info(
                    f"file_move_simulation | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            else:

                shutil.move(source_path, destination_path)

                log_info(
                    f"file_moved | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            # -------------------------------------------------
            # SUCCESS TRACKING
            # -------------------------------------------------
            total_moved += 1
            category_summary[category] = (
                category_summary.get(category, 0) + 1
            )

        # -------------------------------------------------
        # GLOBAL OPERATION FAILURE SAFETY NET
        # -------------------------------------------------
        except Exception as e:

            # This ensures ANY unexpected failure does NOT break pipeline
            log_error(
                f"move_failed | "
                f"reason=unexpected_operation_failure "
                f"file={op.get('file') if isinstance(op, dict) else None}",
                error=e
            )

    # -------------------------------------------------
    # SUMMARY (DEFENSIVE FINALIZATION)
    # -------------------------------------------------
    try:
        summary_parts = [f"total={total_moved}"]

        for cat, count in category_summary.items():
            summary_parts.append(f"{cat}={count}")

        summary_parts.append(f"dry_run={dry_run}")

        log_info("move_summary | " + " ".join(summary_parts))

    except Exception as e:
        log_error("move_summary_failed | reason=summary_build_error", error=e)

    log_info("move_complete")