"""
Smart File Organizer - File Filtering & Skip Policy Layer

This module centralizes filesystem item filtering rules used during
the discovery pipeline.

Primary Responsibilities:
- Validate basic filesystem item integrity
- Apply skip policies for unsupported or unsafe items
- Handle hidden file filtering
- Handle symbolic link filtering
- Provide deterministic skip decisions
- Return machine-readable skip reasons

Architecture Role:
This module acts as the policy layer for pre-processing decisions
during directory discovery.

The filtering system determines whether filesystem entities should:
- continue through the pipeline
- be excluded safely before classification

This module contains NO:
- scanning logic
- classification logic
- filesystem mutation logic
- execution planning

Filtering Philosophy:
Filtering decisions are:
- deterministic
- centralized
- safety-oriented
- observable
- config-driven

Contract Guarantees:
The module guarantees stable tuple-based responses:

    (
        skip: bool,
        reason: str | None
    )

Returned skip reasons are part of the application's structured
logging contract and are intended to remain:
- machine-readable
- stable
- deterministic
- cross-module consistent

Failure Handling Strategy:
Invalid filesystem inputs are treated as skip conditions rather than
raising exceptions, prioritizing pipeline resilience and safe
continuation behavior.

Observability:
Skip reasons generated by this module are propagated into the
structured logging system to provide:
- filtering traceability
- debugging clarity
- operational transparency

Design Principles:
- Centralized filtering ownership
- Defensive programming
- Stable contracts
- Config-driven behavior
- Pipeline safety guarantees
- Deterministic filtering decisions
"""

# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
# Import required libraries
import os


# -------------------------------------------------
# HELPER: Unified skip decision engine
# -------------------------------------------------
def should_skip_item(
    filename: str,
    full_path: str,
    ignore_hidden: bool,
    ignore_symlinks: bool
):
    """
    Determines whether a filesystem item should be skipped.

    Returns:
        tuple:
            (
                skip: bool,
                reason: str | None
            )

    Possible reasons:
    - invalid_filename_type
    - empty_filename
    - invalid_path_type
    - empty_path
    - hidden_file
    - symlink
    """

    # -------------------------------------------------
    # VALIDATION: filename safety
    # -------------------------------------------------
    if not isinstance(filename, str):
        return True, "invalid_filename_type"

    if not filename.strip():
        return True, "empty_filename"

    # -------------------------------------------------
    # VALIDATION: path safety
    # -------------------------------------------------
    if not isinstance(full_path, str):
        return True, "invalid_path_type"

    if not full_path.strip():
        return True, "empty_path"

    # -------------------------------------------------
    # RULE 1: Hidden files
    # -------------------------------------------------
    # Hidden files typically include system metadata:
    # e.g. .DS_Store, .env, .gitignore
    if ignore_hidden and filename.startswith("."):
        return True, "hidden_file"

    # -------------------------------------------------
    # RULE 2: Symlinks
    # -------------------------------------------------
    # Symlinks can point outside the target directory,
    # so we avoid following them for safety reasons.
    if ignore_symlinks and os.path.islink(full_path):
        return True, "symlink"

    # -------------------------------------------------
    # DEFAULT: do not skip
    # -------------------------------------------------
    return False, None