# -------------------------------------------------
# ROLLBACK COORDINATOR
# -------------------------------------------------
"""
Smart File Organizer - Rollback Coordinator

This module orchestrates the rollback workflow.

Responsibilities:
- Load persisted execution reports
- Coordinate rollback planning
- Coordinate rollback execution
- Preserve rollback workflow boundaries
- Return rollback-stage reports

Architecture Role:
This file intentionally contains NO logic related to:
- filesystem discovery
- file filtering
- file classification
- execution planning
- filesystem mutation implementation
- report persistence
- CLI presentation

Instead, it functions as the rollback orchestration layer
responsible for wiring together rollback-specific components.

Rollback Pipeline Overview:
persisted execution report
→ rollback planning
→ rollback execution
→ rollback report

Rollback Components:
- reporting/loader.py:
    Loads persisted execution reports
- rollback/planner.py:
    Builds rollback intent
- rollback/executor.py:
    Executes or simulates rollback operations

Design Principles:
- minimal orchestration
- separation of concerns
- deterministic rollback workflow
- controlled rollback boundaries
- contract-first rollback flow
- structured observability

Contract Usage:
This module consumes persisted ExecutionReport contracts and
returns RollbackReport contracts generated by the rollback executor.

Failure Contract:
- returns None if no execution report is available
- returns a valid RollbackReport on successful rollback workflow
- delegates planning and execution details to rollback modules
"""

# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
from core.contracts import (
    RollbackReport
)

from tasks.reporting.loader import load_latest_execution_report
from tasks.rollback.planner import build_rollback_plan
from tasks.rollback.executor import execute_rollback_plan

from utils.logger import log_info, log_warning


# -------------------------------------------------
# PUBLIC: Rollback latest execution
# -------------------------------------------------
def rollback_latest_execution(
    reports_directory: str,
    execution_reports_directory: str,
    dry_run: bool
) -> RollbackReport | None:
    """
    Executes rollback workflow for the latest persisted execution report.

    RETURNS:
        RollbackReport | None

    IMPORTANT:
    This function coordinates rollback only.
    It does NOT build rollback operations directly and does NOT
    perform filesystem mutations itself.
    """

    log_info(
        f"rollback_workflow_start | "
        f"dry_run={dry_run}"
    )

    # -------------------------------------------------
    # STEP 1: LOAD LATEST EXECUTION REPORT
    # -------------------------------------------------
    execution_report = load_latest_execution_report(
        reports_directory,
        execution_reports_directory
    )

    if execution_report is None:

        log_warning(
            "rollback_skipped | "
            "reason=no_execution_report"
        )

        return None

    # -------------------------------------------------
    # STEP 2: BUILD ROLLBACK PLAN
    # -------------------------------------------------
    rollback_plan = build_rollback_plan(
        execution_report
    )

    log_info(
        f"rollback_plan_ready | "
        f"operations={len(rollback_plan.operations)} "
        f"skipped={len(rollback_plan.skipped)}"
    )

    # -------------------------------------------------
    # STEP 3: EXECUTE ROLLBACK PLAN
    # -------------------------------------------------
    rollback_report = execute_rollback_plan(
        rollback_plan,
        dry_run
    )

    log_info(
        f"rollback_workflow_complete | "
        f"processed={rollback_report.total_processed} "
        f"failed={rollback_report.total_failed} "
        f"dry_run={rollback_report.dry_run}"
    )

    return rollback_report