# -------------------------------------------------
# ROLLBACK EXECUTOR
# -------------------------------------------------
"""
Smart File Organizer - Rollback Executor

This module executes deterministic rollback operations
generated by the rollback planning layer.

Responsibilities:
- Execute rollback filesystem mutations
- Simulate rollback operations in dry-run mode
- Validate rollback source paths at runtime
- Validate rollback destination conflicts at runtime
- Isolate rollback operation failures
- Build rollback-stage reports
- Preserve rollback observability

Architecture Role:
This file intentionally contains NO logic related to:
- filesystem discovery
- file filtering
- file classification
- execution planning
- rollback planning
- pipeline orchestration
- report persistence
- CLI presentation

Instead, it functions as the low-level rollback execution layer
responsible for applying reverse filesystem mutations generated
by rollback/planner.py.

Rollback Overview:
RollbackPlan
→ runtime filesystem validation
→ filesystem rollback mutations / dry-run simulation
→ operation-level rollback results
→ RollbackReport

Rollback Contract:
Consumes:
- RollbackPlan
- dry_run flag

Produces:
- RollbackReport

Guarantees:
- isolated per-operation rollback execution
- safe continuation after failures
- deterministic rollback behavior
- no rollback planning decisions during execution
- structured rollback report generation
- operation-level rollback result tracking

Design Principles:
- rollback-only responsibility
- deterministic execution
- trusted rollback contracts
- per-operation isolation
- defensive filesystem handling
- stable rollback structures
- contract-first reporting boundary
- structured observability
"""

# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
# Import standard library dependencies
import os
import shutil

# Import internal project modules
from utils.logger import log_info, log_warning, log_error

# Import shared contracts
from core.contracts import (
    RollbackOperation,
    RollbackPlan,
    RollbackReport,
    RollbackResult
)

from core.events import (
    ROLLBACK_START,
    ROLLBACK_COMPLETE,
    ROLLBACK_FAILED,
    ROLLBACK_SIMULATION,
    ROLLBACK_SUMMARY
)


# -------------------------------------------------
# PRIVATE: Build rollback result
# -------------------------------------------------
def _build_rollback_result(
    operation: RollbackOperation,
    status: str,
    reason: str | None = None
) -> RollbackResult:
    """
    Builds an operation-level rollback result.

    PURPOSE:
    - centralize RollbackResult construction
    - keep rollback branches readable
    - preserve consistent result metadata
    """

    return RollbackResult(
        category=operation.category,
        file=operation.file,
        source_path=operation.source_path,
        destination_path=operation.destination_path,
        status=status,
        reason=reason
    )


# -------------------------------------------------
# PUBLIC: Execute rollback operations
# -------------------------------------------------
def execute_rollback_plan(
    plan: RollbackPlan,
    dry_run: bool
) -> RollbackReport:
    """
    Executes rollback operations generated by rollback/planner.py.

    ROLLBACK CONTRACT:
    - Each rollback operation is fully independent
    - Failure in one operation MUST NOT affect others
    - No rollback planning occurs here
    - Every rollback operation produces a RollbackResult
    """

    log_info(
        f"{ROLLBACK_START} | "
        f"operations={len(plan.operations)} "
        f"dry_run={dry_run}"
    )

    # -------------------------------------------------
    # ROLLBACK STATE
    # -------------------------------------------------
    total_processed = 0
    total_failed = 0
    rollback_results: list[RollbackResult] = []

    # -------------------------------------------------
    # ROLLBACK LOOP (ISOLATED PER OPERATION)
    # -------------------------------------------------
    for operation in plan.operations:

        try:

            source_path = operation.source_path
            destination_path = operation.destination_path
            file = operation.file

            # -------------------------------------------------
            # SOURCE VALIDATION
            # -------------------------------------------------
            if not os.path.exists(source_path):

                total_failed += 1

                rollback_results.append(
                    _build_rollback_result(
                        operation,
                        status="failed",
                        reason="rollback_source_missing"
                    )
                )

                log_warning(
                    f"{ROLLBACK_FAILED} | "
                    f"reason=rollback_source_missing "
                    f"file={file} "
                    f"source_path={source_path}"
                )

                continue

            # -------------------------------------------------
            # DESTINATION CONFLICT VALIDATION
            # -------------------------------------------------
            if os.path.exists(destination_path):

                total_failed += 1

                rollback_results.append(
                    _build_rollback_result(
                        operation,
                        status="failed",
                        reason="rollback_destination_exists"
                    )
                )

                log_warning(
                    f"{ROLLBACK_FAILED} | "
                    f"reason=rollback_destination_exists "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

                continue

            # -------------------------------------------------
            # ROLLBACK PHASE
            # -------------------------------------------------
            if dry_run:

                rollback_results.append(
                    _build_rollback_result(
                        operation,
                        status="simulated"
                    )
                )

                log_info(
                    f"{ROLLBACK_SIMULATION} | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            else:

                shutil.move(
                    source_path,
                    destination_path
                )

                rollback_results.append(
                    _build_rollback_result(
                        operation,
                        status="success"
                    )
                )

                log_info(
                    f"{ROLLBACK_COMPLETE} | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            total_processed += 1

        except Exception as e:

            total_failed += 1

            rollback_results.append(
                _build_rollback_result(
                    operation,
                    status="failed",
                    reason="unexpected_rollback_failure"
                )
            )

            log_error(
                f"{ROLLBACK_FAILED} | "
                f"reason=unexpected_rollback_failure "
                f"file={operation.file}",
                error=e
            )

    rollback_report = RollbackReport(
        dry_run=dry_run,
        total_processed=total_processed,
        total_failed=total_failed,
        results=rollback_results
    )

    log_info(
        f"{ROLLBACK_SUMMARY} | "
        f"processed={rollback_report.total_processed} "
        f"failed={rollback_report.total_failed} "
        f"dry_run={rollback_report.dry_run}"
    )

    log_info(f"{ROLLBACK_COMPLETE} | ")

    return rollback_report