# -------------------------------------------------
# EXECUTION ENGINE
# -------------------------------------------------
"""
Smart File Organizer - Filesystem Execution Engine

This module executes deterministic filesystem operations
generated by the execution planning layer.

Responsibilities:
- Execute filesystem mutations
- Create destination folders safely
- Move files deterministically
- Isolate operation failures
- Preserve execution observability

Architecture Role:
This file intentionally contains NO logic related to:
- filesystem discovery
- file filtering
- classification
- execution planning
- pipeline orchestration

Instead, it functions as the low-level execution layer
responsible for applying filesystem mutations generated
by planner.py.

Execution Overview:
execution plan
→ folder preparation
→ filesystem mutations
→ execution summary

Execution Contract:
Consumes:
- list[ExecutionOperation]

Guarantees:
- isolated per-operation execution
- safe continuation after failures
- deterministic execution behavior
- no planning decisions during execution

Design Principles:
- execution-only responsibility
- deterministic execution
- trusted execution contracts
- per-operation isolation
- defensive filesystem handling
- stable execution structures
- structured observability

Observability:
Structured logs are emitted throughout execution to provide:
- execution traceability
- filesystem mutation visibility
- operation diagnostics
- failure localization
"""

# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
# Import standard library dependencies
import os
import shutil

# Import internal project modules
from utils.logger import log_info, log_warning, log_error

# Import shared contracts
from core.contracts import ExecutionOperation

# import events from core.events
from core.events import (
    MOVE_START,
    MOVE_COMPLETE,
    MOVE_SUMMARY,
    MOVE_SUMMARY_FAILED,
    MOVE_FAILED,
    MOVE_SKIP,
    FOLDER_CREATED,
    FOLDER_CREATE_FAILED,
    FOLDER_CREATE_SIMULATION,
    FILE_MOVED,
    FILE_MOVE_SIMULATION
)

# -------------------------------------------------
# PUBLIC: Execute filesystem operations
# -------------------------------------------------
def move_files(
    operations: list[ExecutionOperation],
    dry_run: bool
):
    """
    Executes filesystem operations generated by planner.py

    EXECUTION CONTRACT:
    - Each operation is fully independent
    - Failure in one operation MUST NOT affect others
    - No decision making or planning occurs here
    """

    log_info(
        f"{MOVE_START} | "
        f"operations={len(operations)} "
        f"dry_run={dry_run}"
    )

    # -------------------------------------------------
    # EXECUTION STATE
    # -------------------------------------------------
    total_moved = 0
    category_summary = {}
    created_folders = set()

    # -------------------------------------------------
    # EXECUTION LOOP (ISOLATED PER OPERATION)
    # -------------------------------------------------
    for operation in operations:

        # =================================================
        # OPERATION ISOLATION BOUNDARY
        # =================================================
        # Each operation is fully independent and failure-safe
        try:

            source_path = operation.source_path
            destination_path = operation.destination_path
            category = operation.category
            file = operation.file
            folder_name = operation.folder_name

            # -------------------------------------------------
            # FOLDER CREATION (SAFE + ONCE PER FOLDER)
            # -------------------------------------------------
            if folder_name and folder_name not in created_folders:

                created_folders.add(folder_name)

                if dry_run:

                    log_info(
                        f"{FOLDER_CREATE_SIMULATION} | "
                        f"folder={folder_name}"
                    )

                else:

                    try:

                        os.makedirs(
                            os.path.dirname(destination_path),
                            exist_ok=True
                        )

                        log_info(
                            f"{FOLDER_CREATED} | "
                            f"folder={folder_name}"
                        )

                    except Exception as e:

                        log_error(
                            f"{FOLDER_CREATE_FAILED} | "
                            f"reason=os_error "
                            f"destination_path={destination_path}",
                            error=e
                        )

                        continue

            # -------------------------------------------------
            # SOURCE VALIDATION
            # -------------------------------------------------
            # Runtime filesystem validation.
            #
            # Filesystem state may change between:
            # - discovery stage
            # - execution stage
            #
            # Therefore runtime validation remains necessary
            # even with trusted execution contracts.
            if not os.path.exists(source_path):

                log_warning(
                    f"{MOVE_SKIP} | "
                    f"reason=file_missing "
                    f"file={file} "
                    f"source_path={source_path}"
                )

                continue

            # -------------------------------------------------
            # EXECUTION PHASE
            # -------------------------------------------------
            if dry_run:

                log_info(
                    f"{FILE_MOVE_SIMULATION} | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            else:

                shutil.move(
                    source_path,
                    destination_path
                )

                log_info(
                    f"{FILE_MOVED} | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            # -------------------------------------------------
            # SUCCESS TRACKING
            # -------------------------------------------------
            total_moved += 1

            category_summary[category] = (
                category_summary.get(category, 0) + 1
            )

        # -------------------------------------------------
        # GLOBAL OPERATION FAILURE SAFETY NET
        # -------------------------------------------------
        except Exception as e:

            # This ensures ANY unexpected failure
            # does NOT break pipeline execution.
            log_error(
                f"{MOVE_FAILED} | "
                f"reason=unexpected_operation_failure "
                f"file={operation.file}",
                error=e
            )

    # -------------------------------------------------
    # SUMMARY (DEFENSIVE FINALIZATION)
    # -------------------------------------------------
    try:

        summary_parts = [f"total={total_moved}"]

        for cat, count in category_summary.items():
            summary_parts.append(f"{cat}={count}")

        summary_parts.append(f"dry_run={dry_run}")

        log_info(
            f"{MOVE_SUMMARY} | "
            + " ".join(summary_parts)
        )

    except Exception as e:

        log_error(
            f"{MOVE_SUMMARY_FAILED} | "
            "reason=summary_build_error",
            error=e
        )

    log_info(MOVE_COMPLETE)