# -------------------------------------------------
# FILESYSTEM MOVER
# -------------------------------------------------
"""
Smart File Organizer - Filesystem Mover

This module executes deterministic filesystem move operations
generated by the execution planning layer.

Responsibilities:
- Execute filesystem mutations
- Create destination folders safely
- Move files deterministically
- Simulate moves in dry-run mode
- Isolate operation failures
- Build mover-stage execution reports
- Preserve execution observability

Architecture Role:
This file intentionally contains NO logic related to:
- filesystem discovery
- file filtering
- classification
- execution planning
- pipeline orchestration
- application-level report assembly

Instead, it functions as the low-level mover stage responsible
for applying filesystem mutations generated by planner.py.

This module owns mover result aggregation but does NOT assemble
application-level reports.

Mover Overview:
execution plan
→ folder preparation
→ filesystem mutations / dry-run simulation
→ operation-level execution results
→ mover report

Execution Contract:
Consumes:
- list[ExecutionOperation]
- dry_run flag

Produces:
- MoverReport

Guarantees:
- isolated per-operation execution
- safe continuation after failures
- deterministic execution behavior
- no planning decisions during execution
- structured mover report generation
- operation-level execution result tracking

Design Principles:
- mover-only responsibility
- deterministic execution
- trusted execution contracts
- per-operation isolation
- defensive filesystem handling
- stable execution structures
- contract-first reporting boundary
- structured observability

Observability:
Structured logs are emitted throughout execution to provide:
- mover traceability
- filesystem mutation visibility
- operation diagnostics
- failure localization
"""

# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
# Import standard library dependencies
import os
import shutil

# Import internal project modules
from utils.logger import log_info, log_warning, log_error

# Import shared contracts
from core.contracts import (
    ExecutionOperation,
    ExecutionResult,
    MoverReport,
    CategoryReport
)

# Import events from core.events
from core.events import (
    MOVE_START,
    MOVE_EXECUTION_COMPLETE,
    MOVE_SUMMARY,
    MOVE_SUMMARY_FAILED,
    MOVE_FAILED,
    FOLDER_CREATED,
    FOLDER_CREATE_FAILED,
    FOLDER_CREATE_SIMULATION,
    FILE_MOVED,
    FILE_MOVE_SIMULATION
)


# -------------------------------------------------
# PRIVATE: Build category summary reports
# -------------------------------------------------
def _build_category_reports(
    category_summary: dict[str, int]
) -> list[CategoryReport]:
    """
    Builds structured category report contracts from
    mover category counters.

    PURPOSE:
    - isolate report contract construction
    - keep execution loop focused on filesystem work
    - preserve deterministic reporting output

    IMPORTANT:
    This helper only transforms already-collected
    mover data into reporting contracts.
    It does NOT perform reporting orchestration,
    rendering, exporting, or persistence.
    """

    category_reports = []

    for category, files in category_summary.items():

        category_reports.append(
            CategoryReport(
                category=category,
                files=files
            )
        )

    return category_reports


# -------------------------------------------------
# PRIVATE: Build execution result
# -------------------------------------------------
def _build_execution_result(
    operation: ExecutionOperation,
    status: str,
    reason: str | None = None
) -> ExecutionResult:
    """
    Builds an operation-level execution result.

    PURPOSE:
    - centralize ExecutionResult construction
    - keep execution branches readable
    - preserve consistent result metadata
    """

    return ExecutionResult(
        category=operation.category,
        file=operation.file,
        source_path=operation.source_path,
        destination_path=operation.destination_path,
        status=status,
        reason=reason
    )


# -------------------------------------------------
# PUBLIC: Execute filesystem operations
# -------------------------------------------------
def move_files(
    operations: list[ExecutionOperation],
    dry_run: bool
) -> MoverReport:
    """
    Executes filesystem operations generated by planner.py.

    EXECUTION CONTRACT:
    - Each operation is fully independent
    - Failure in one operation MUST NOT affect others
    - No decision making or planning occurs here
    - Every operation produces an ExecutionResult
    """

    log_info(
        f"{MOVE_START} | "
        f"operations={len(operations)} "
        f"dry_run={dry_run}"
    )

    # -------------------------------------------------
    # EXECUTION STATE
    # -------------------------------------------------
    total_processed = 0
    total_failed = 0
    category_summary: dict[str, int] = {}
    execution_results: list[ExecutionResult] = []
    created_folders = set()

    # -------------------------------------------------
    # EXECUTION LOOP (ISOLATED PER OPERATION)
    # -------------------------------------------------
    for operation in operations:

        # =================================================
        # OPERATION ISOLATION BOUNDARY
        # =================================================
        # Each operation is fully independent and failure-safe
        try:

            source_path = operation.source_path
            destination_path = operation.destination_path
            category = operation.category
            file = operation.file
            folder_name = operation.folder_name
            
            # -------------------------------------------------
            # SOURCE VALIDATION
            # -------------------------------------------------
            # Runtime filesystem validation.
            #
            # Filesystem state may change between:
            # - discovery stage
            # - mover stage
            #
            # Therefore runtime validation remains necessary
            # even with trusted execution contracts.
            if not os.path.exists(source_path):

                total_failed += 1

                execution_results.append(
                    _build_execution_result(
                        operation,
                        status="failed",
                        reason="file_missing"
                    )
                )

                log_warning(
                    f"{MOVE_FAILED} | "
                    f"reason=file_missing "
                    f"file={file} "
                    f"source_path={source_path}"
                )

                continue

            
            # -------------------------------------------------
            # FOLDER CREATION (SAFE + ONCE PER FOLDER)
            # -------------------------------------------------
            if folder_name and folder_name not in created_folders:

                created_folders.add(folder_name)

                if dry_run:

                    log_info(
                        f"{FOLDER_CREATE_SIMULATION} | "
                        f"folder={folder_name}"
                    )

                else:

                    try:

                        os.makedirs(
                            os.path.dirname(destination_path),
                            exist_ok=True
                        )

                        log_info(
                            f"{FOLDER_CREATED} | "
                            f"folder={folder_name}"
                        )

                    except Exception as e:

                        total_failed += 1

                        execution_results.append(
                            _build_execution_result(
                                operation,
                                status="failed",
                                reason="folder_create_failed"
                            )
                        )

                        log_error(
                            f"{FOLDER_CREATE_FAILED} | "
                            f"reason=os_error "
                            f"destination_path={destination_path}",
                            error=e
                        )

                        continue


            # -------------------------------------------------
            # EXECUTION PHASE
            # -------------------------------------------------
            if dry_run:

                execution_results.append(
                    _build_execution_result(
                        operation,
                        status="simulated"
                    )
                )

                log_info(
                    f"{FILE_MOVE_SIMULATION} | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            else:

                shutil.move(
                    source_path,
                    destination_path
                )

                execution_results.append(
                    _build_execution_result(
                        operation,
                        status="success"
                    )
                )

                log_info(
                    f"{FILE_MOVED} | "
                    f"file={file} "
                    f"destination_path={destination_path}"
                )

            # -------------------------------------------------
            # SUCCESS TRACKING
            # -------------------------------------------------
            total_processed += 1

            category_summary[category] = (
                category_summary.get(category, 0) + 1
            )

        # -------------------------------------------------
        # GLOBAL OPERATION FAILURE SAFETY NET
        # -------------------------------------------------
        except Exception as e:

            total_failed += 1

            execution_results.append(
                _build_execution_result(
                    operation,
                    status="failed",
                    reason="unexpected_operation_failure"
                )
            )

            # This ensures ANY unexpected failure
            # does NOT break pipeline execution.
            log_error(
                f"{MOVE_FAILED} | "
                f"reason=unexpected_operation_failure "
                f"file={operation.file}",
                error=e
            )

    # -------------------------------------------------
    # REPORT CONTRACT CONSTRUCTION
    # -------------------------------------------------
    category_reports = _build_category_reports(
        category_summary
    )

    mover_report = MoverReport(
        dry_run=dry_run,
        total_processed=total_processed,
        total_failed=total_failed,
        categories=category_reports,
        results=execution_results
    )

    # -------------------------------------------------
    # SUMMARY LOGGING (DEFENSIVE FINALIZATION)
    # -------------------------------------------------
    try:

        summary_parts = [
            f"processed={mover_report.total_processed}",
            f"failed={mover_report.total_failed}"
        ]

        for category_report in mover_report.categories:

            summary_parts.append(
                f"{category_report.category}={category_report.files}"
            )

        summary_parts.append(
            f"dry_run={mover_report.dry_run}"
        )

        log_info(
            f"{MOVE_SUMMARY} | "
            + " ".join(summary_parts)
        )

    except Exception as e:

        log_error(
            f"{MOVE_SUMMARY_FAILED} | "
            "reason=summary_build_error",
            error=e
        )

    log_info(MOVE_EXECUTION_COMPLETE)

    return mover_report