# -------------------------------------------------
# EXECUTION PLANNER
# -------------------------------------------------
"""
Smart File Organizer - Execution Planner

This module transforms classified discovery data into a
deterministic execution plan BEFORE filesystem mutations occur.

Responsibilities:
- Build deterministic execution structures
- Resolve destination paths
- Register required folders
- Generate execution operations
- Generate structured skipped-operation diagnostics

Architecture Role:
This file intentionally contains NO logic related to:
- filesystem scanning
- file filtering
- file classification
- filesystem mutations
- execution orchestration

Instead, it functions as the execution planning layer
responsible for transforming classified discovery data
into executable filesystem operations.

Planning Overview:
classified discovery data
→ destination resolution
→ execution operation generation
→ deterministic execution plan

Input Contract:
Consumes a ClassifiedDiscovery dataset generated by
the discovery subsystem.

Output Contract:
Returns a fully structured ExecutionPlan object.

Failure Contract:
- never crashes
- returns safe fallback plans
- preserves deterministic structure
- guarantees executor-safe output

Design Principles:
- deterministic planning
- execution-only planning
- explicit execution contracts
- trusted pipeline contracts
- stable execution structures
- structured observability

Observability:
Structured logs are emitted throughout execution to provide:
- planning traceability
- execution visibility
- contract diagnostics
- failure localization
"""

# -------------------------------------------------
# IMPORTS
# -------------------------------------------------
# Import required libraries
import os

# Import modules from the project
from utils.logger import log_info

# Import shared contracts
from core.contracts import (
    ClassifiedDiscovery,
    ExecutionOperation,
    ExecutionPlan,
    SkippedOperation
)

from core.events import (
    PLAN_BUILD_START,
    PLAN_BUILD_COMPLETE,
)

# -------------------------------------------------
# PUBLIC: Build execution plan
# -------------------------------------------------
def build_execution_plan(
    path: str,
    classified_data: ClassifiedDiscovery,
    folder_prefix: str
) -> ExecutionPlan:
    """
    Builds deterministic filesystem execution plan.

    RETURNS:
        ExecutionPlan
    """

    log_info(f"{PLAN_BUILD_START} | "
             f"path={path}"
        )

    # -------------------------------------------------
    # PLAN STRUCTURE
    # -------------------------------------------------
    # Central deterministic execution contract
    # shared between:
    # - dry-run mode
    # - real execution mode
    plan = ExecutionPlan(
        folders_to_create=[],
        operations=[],
        skipped=[]
    )

    planned_folders = set()

    # -------------------------------------------------
    # CATEGORY ITERATION
    # -------------------------------------------------
    for category, files in classified_data.items():

        # Internal discovery-only tracking bucket
        if category == "directories":
            continue

        # Ignore empty categories
        if not files:
            continue

        # -------------------------------------------------
        # DESTINATION RESOLUTION
        # -------------------------------------------------
        folder_name = f"{folder_prefix}-{category}"

        destination_folder = os.path.join(
            path,
            folder_name
        )

        # -------------------------------------------------
        # FOLDER REGISTRATION
        # -------------------------------------------------
        # Register once to avoid duplicate creation entries
        if destination_folder not in planned_folders:

            planned_folders.add(destination_folder)

            if not os.path.exists(destination_folder):

                plan.folders_to_create.append(
                    destination_folder
                )

        # -------------------------------------------------
        # FILE ITERATION
        # -------------------------------------------------
        for file in files:

            # -------------------------------------------------
            # PATH RESOLUTION
            # -------------------------------------------------
            source_path = os.path.join(path, file)

            destination_path = os.path.join(
                destination_folder,
                file
            )

            # -------------------------------------------------
            # SOURCE VALIDATION
            # -------------------------------------------------
            # Runtime filesystem validation.
            #
            # Filesystem state may change between:
            # - discovery stage
            # - planning stage
            #
            # Therefore this validation remains necessary
            # even with trusted pipeline contracts.
            if not os.path.exists(source_path):

                plan.skipped.append(
                    SkippedOperation(
                        reason="file_missing",
                        file=file,
                        category=category,
                        source_path=source_path
                    )
                )

                continue

            # -------------------------------------------------
            # FINAL EXECUTION CONTRACT
            # -------------------------------------------------
            # Structure consumed directly by executor.py
            # without additional transformation.
            plan.operations.append(
                ExecutionOperation(
                    category=category,
                    file=file,
                    source_path=source_path,
                    destination_path=destination_path,
                    folder_name=folder_name
                )
            )

    # -------------------------------------------------
    # FINAL SUMMARY
    # -------------------------------------------------
    log_info(
        f"{PLAN_BUILD_COMPLETE} | "
        f"folders={len(plan.folders_to_create)} "
        f"operations={len(plan.operations)} "
        f"skipped={len(plan.skipped)}"
    )

    return plan